#!/usr/bin/env npx tsx
/**
 * Analysis script for 6-Turn Random Control experiment
 * Generates tables and statistics for paper integration
 * 
 * Output: paper/tables/6turn-rc-results.tex
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { glob } from 'glob';

interface Trial {
  model: string;
  anchor: number;
  initialSentence: number;
  finalSentence: number;
  prosecutorResponse?: string;
}

interface ModelStats {
  model: string;
  modelShort: string;
  baseline: number;
  lowAnchor: {
    anchor: number;
    n: number;
    initialMean: number;
    initialStd: number;
    finalMean: number;
    finalStd: number;
    changed: number;
    revisionRate: number;
  };
  highAnchor: {
    anchor: number;
    n: number;
    initialMean: number;
    initialStd: number;
    finalMean: number;
    finalStd: number;
    changed: number;
    revisionRate: number;
  };
  overallRevisionRate: number;
}

const MODEL_BASELINES: Record<string, number> = {
  'anthropic/claude-haiku-4.5': 29.1,
  'anthropic/claude-sonnet-4-6': 24.1,
  'anthropic/claude-opus-4-6': 18.0,
  'openai/gpt-5.2': 31.8,
};

const MODEL_SHORT: Record<string, string> = {
  'anthropic/claude-haiku-4.5': 'Haiku 4.5',
  'anthropic/claude-sonnet-4-6': 'Sonnet 4.6',
  'anthropic/claude-opus-4-6': 'Opus 4.6',
  'openai/gpt-5.2': 'GPT-5.2',
};

function std(arr: number[]): number {
  const mean = arr.reduce((a, b) => a + b, 0) / arr.length;
  const variance = arr.reduce((sum, x) => sum + Math.pow(x - mean, 2), 0) / arr.length;
  return Math.sqrt(variance);
}

async function loadTrials(): Promise<Trial[]> {
  const files = await glob('results/6turn-rc-englich-*.jsonl');
  const trials: Trial[] = [];
  
  for (const file of files) {
    const content = await readFile(file, 'utf-8');
    const lines = content.trim().split('\n').filter(l => l.trim());
    for (const line of lines) {
      try {
        trials.push(JSON.parse(line));
      } catch {}
    }
  }
  
  return trials;
}

function analyzeModel(trials: Trial[], model: string): ModelStats | null {
  const modelTrials = trials.filter(t => t.model === model);
  if (modelTrials.length === 0) return null;
  
  const baseline = MODEL_BASELINES[model] || 24;
  const lowAnchorValue = Math.round(baseline * 0.5);
  const highAnchorValue = Math.round(baseline * 1.5);
  
  const lowTrials = modelTrials.filter(t => t.anchor <= baseline);
  const highTrials = modelTrials.filter(t => t.anchor > baseline);
  
  const analyzeCondition = (condTrials: Trial[]) => {
    if (condTrials.length === 0) return null;
    const initials = condTrials.map(t => t.initialSentence).filter(x => x != null);
    const finals = condTrials.map(t => t.finalSentence).filter(x => x != null);
    const changed = condTrials.filter(t => t.initialSentence !== t.finalSentence).length;
    
    return {
      anchor: condTrials[0]?.anchor || 0,
      n: condTrials.length,
      initialMean: initials.reduce((a, b) => a + b, 0) / initials.length,
      initialStd: std(initials),
      finalMean: finals.reduce((a, b) => a + b, 0) / finals.length,
      finalStd: std(finals),
      changed,
      revisionRate: (changed / condTrials.length) * 100,
    };
  };
  
  const low = analyzeCondition(lowTrials);
  const high = analyzeCondition(highTrials);
  
  if (!low || !high) return null;
  
  const totalChanged = low.changed + high.changed;
  const totalN = low.n + high.n;
  
  return {
    model,
    modelShort: MODEL_SHORT[model] || model,
    baseline,
    lowAnchor: low,
    highAnchor: high,
    overallRevisionRate: (totalChanged / totalN) * 100,
  };
}

async function generateLatexTable(stats: ModelStats[]): Promise<string> {
  let tex = `% Auto-generated by analysis-6turn-rc.ts
% Generated: ${new Date().toISOString()}

\\begin{table}[htbp]
\\centering
\\caption{6-Turn Random Control Results: Revision Rates by Model}
\\label{tab:6turn-rc-results}
\\begin{tabular}{lcccccc}
\\toprule
\\textbf{Model} & \\textbf{Anchor} & \\textbf{n} & \\textbf{Initial} & \\textbf{Final} & \\textbf{Changed} & \\textbf{Rate} \\\\
\\midrule
`;

  for (const s of stats) {
    tex += `${s.modelShort} & Low (${s.lowAnchor.anchor}mo) & ${s.lowAnchor.n} & ${s.lowAnchor.initialMean.toFixed(1)} & ${s.lowAnchor.finalMean.toFixed(1)} & ${s.lowAnchor.changed} & ${s.lowAnchor.revisionRate.toFixed(1)}\\% \\\\\n`;
    tex += `& High (${s.highAnchor.anchor}mo) & ${s.highAnchor.n} & ${s.highAnchor.initialMean.toFixed(1)} & ${s.highAnchor.finalMean.toFixed(1)} & ${s.highAnchor.changed} & ${s.highAnchor.revisionRate.toFixed(1)}\\% \\\\\n`;
    tex += `\\midrule\n`;
  }

  tex += `\\bottomrule
\\end{tabular}
\\end{table}

% Summary statistics
% Overall revision rates:
`;

  for (const s of stats) {
    tex += `% ${s.modelShort}: ${s.overallRevisionRate.toFixed(1)}%\n`;
  }

  return tex;
}

async function generateMarkdownSummary(stats: ModelStats[]): Promise<string> {
  let md = `# 6-Turn Random Control Analysis

Generated: ${new Date().toISOString()}

## Results by Model

| Model | Anchor | n | Initial | Final | Changed | Rate |
|-------|--------|---|---------|-------|---------|------|
`;

  for (const s of stats) {
    md += `| ${s.modelShort} | Low (${s.lowAnchor.anchor}mo) | ${s.lowAnchor.n} | ${s.lowAnchor.initialMean.toFixed(1)} | ${s.lowAnchor.finalMean.toFixed(1)} | ${s.lowAnchor.changed} | ${s.lowAnchor.revisionRate.toFixed(1)}% |\n`;
    md += `| | High (${s.highAnchor.anchor}mo) | ${s.highAnchor.n} | ${s.highAnchor.initialMean.toFixed(1)} | ${s.highAnchor.finalMean.toFixed(1)} | ${s.highAnchor.changed} | ${s.highAnchor.revisionRate.toFixed(1)}% |\n`;
  }

  md += `\n## Overall Revision Rates\n\n`;
  md += `| Model | Filler + "revised" | SACD (86%) | Gap |\n`;
  md += `|-------|-------------------|------------|-----|\n`;
  
  for (const s of stats) {
    const gap = 86 - s.overallRevisionRate;
    md += `| ${s.modelShort} | ${s.overallRevisionRate.toFixed(1)}% | 86% | ${gap.toFixed(1)}pp |\n`;
  }

  md += `\n## Model Taxonomy\n\n`;
  md += `- **Instruction-following** (Haiku): High response to implicit "revised" cue\n`;
  md += `- **Balanced** (Opus): Moderate response\n`;
  md += `- **Reasoning-anchored** (Sonnet): Resists implicit instruction, needs explicit bias prompts\n`;

  return md;
}

async function main() {
  console.log('Loading trials...');
  const trials = await loadTrials();
  console.log(`Loaded ${trials.length} trials`);

  const models = [...new Set(trials.map(t => t.model))];
  console.log(`Models: ${models.join(', ')}`);

  const stats: ModelStats[] = [];
  for (const model of models) {
    const s = analyzeModel(trials, model);
    if (s) stats.push(s);
  }

  // Sort by revision rate
  stats.sort((a, b) => b.overallRevisionRate - a.overallRevisionRate);

  // Generate outputs
  if (!existsSync('paper/tables')) {
    await mkdir('paper/tables', { recursive: true });
  }

  const tex = await generateLatexTable(stats);
  await writeFile('paper/tables/6turn-rc-results.tex', tex);
  console.log('Generated: paper/tables/6turn-rc-results.tex');

  const md = await generateMarkdownSummary(stats);
  await writeFile('paper/6turn-rc-analysis.md', md);
  console.log('Generated: paper/6turn-rc-analysis.md');

  // Print summary
  console.log('\n=== Summary ===');
  for (const s of stats) {
    console.log(`${s.modelShort}: ${s.overallRevisionRate.toFixed(1)}% revision rate`);
  }
}

main().catch(console.error);
